### PR TITLE
Add additional required packages to Docker build

### PR DESCRIPTION
**Pull request by kwilcox**

### CODE REVIEW

**Comment by kwilcox** [comment]
Please don't merge yet, still needs testing

**Comment by metanomy** [comment]
Getting an error when trying to build with the additional three packages in this change:

ImportError: pandas 0.16.2 is incompatible with numpy < 1.7.0, your numpy version is 1.6.2. Please upgrade numpy to >= 1.7.0 to use pandas version 0.16.2

**Comment by kwilcox** [comment]
@metanomy thanks for the excellent bug reports... I will have a fix for this soon (tomorrow)... stay tuned.

**Comment by metanomy** [comment]
I changed the numpy line in requirements.txt to:
numpy==1.7.1

Now recompiling the image. I'll report the outcome.

**Comment by metanomy** [comment]
I tried two numpy versions - 1.7.1, and 1.7.0, each time got this in the build:

Copying '/usr/local/lSegmentation fault (core dumped)
The command '/bin/sh -c python manage.py collectstatic --noinput' returned a non-zero code: 139

**Comment by kwilcox** [comment]
@metanomy All set, building and running for me now. Let me know that its working for you!

**Comment by metanomy** [comment]
@kwilcox Build success! Appreciate the fast turnaround. Next step for me: display the results of the West Florida Shelf FVCOM model (http://ocgweb.marine.usf.edu/Models/FVCOM/fvcom_index.html) in TerriaJS!

**Comment by kwilcox** [comment]
@metanomy good luck! The model you linked to works well in sci-wms.

selection_052

**Comment by rsignell-usgs** [comment]
@metanomy, I'd be interested in how well your TerriaJS experiments are going.   I started by cloning the australian national map app, and then dinking around with the config: https://gist.github.com/rsignell-usgs/75311f5bbdaeb7219313

This issue on upgrading terriajs may be useful too:https://github.com/TerriaJS/map/issues/2#issuecomment-125781655

And if you are want to query the NGDC catalog via CSW, perhaps this issue:
https://github.com/TerriaJS/terriajs/pull/860

**Comment by metanomy** [comment]
We've kept things pretty basic for now: tampabaymap.org. Our next steps:
- Make sci-wms happy so it will feed the virtual u,v layer from the West
  Florida Shelf FVCOM forecast model to TerriaJS.
- Copy the D3 work from ewatercycle (http://forecast.ewatercycle.org/)
  so we can get chart-ology for the WFS FVCOM.
- Explore how best to display NOAA GNOME-generated animations in
  TampaBayMap (either through wms sequences, or if we're really crazy we'll
  do a COLLADA->gltf model).
- Work with NICTA to modifyTerriaJS in a standard way (e.g., through
  their catalog models:
  https://github.com/TerriaJS/terriajs/tree/master/lib/Models) to support
  live data streaming. Our primary use case is equipping near-coastal and
  inshore protective boom with either typical GIS, or their own AIS
  transmitter, so the area response participants can see where the booms are
  (or where they are drifting).

On Mon, Aug 17, 2015 at 8:54 AM, Rich Signell notifications@github.com
wrote:

> @metanomy https://github.com/metanomy, I'd be interested in how well
> your TerriaJS experiments are going. I started by cloning the australian
> national map app, and then dinking around with the config:
> https://gist.github.com/rsignell-usgs/75311f5bbdaeb7219313
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sci-wms/sci-wms/pull/69#issuecomment-131807449.

## 

Cameron Hunt
President, Metanomy, Inc, 501(c)(3).
Cell: 843.654.4708

**Pull request merged**
