### PR TITLE
sgrid caching and virtual layer rendering

### PR DESCRIPTION
**Pull request by ayan-usgs**
sgrid caching and virtual layer rendering

### CODE REVIEW

**Comment by kwilcox** [comment]
@ayan-usgs let me know when you want me to take a look

**Comment by ayan-usgs** [comment]
@kwilcox,

This is almost there. Just some refactoring and test fixes and it should be good to go. I'll keep you apprised.

**Comment by ayan-usgs** [comment]
@kwilcox,

Can you take a look at this when you get a chance?

getFeature for an sgrid still needs to be implemented, and there are performance issues with getCaps, and with sgrid on the leaflet client, but pysgrid is baked into sci-wms enough to warrant a formal request to merge.

As always, let me know of any improvements you suggest.

Many thanks!

**Comment by kwilcox** [comment]
@ayan-usgs will do!

**Comment by kwilcox** [comment]
Did you come across a dataset that had two variables with `standard_name: time`?

https://github.com/ayan-usgs/sci-wms/blob/e4e49c06df3a3819e6d7d22a4d3a7b445b09636b/wms/models/datasets/sgrid.py#L48-L70

**Comment by kwilcox** [comment]
@ayan-usgs https://github.com/ayan-usgs/sci-wms/pull/1

**Comment by ayan-usgs** [comment]
@kwilcox,

No, I haven't come across any datasets with two variables with `standard_name: time`. While I haven't encountered any such datasets, I was under the impression that they exist. The code https://github.com/ayan-usgs/sci-wms/blob/e4e49c06df3a3819e6d7d22a4d3a7b445b09636b/wms/models/datasets/sgrid.py#L48-L70 could be simplified if multiple variables with `standard_name: time` isn't actually a thing.

**Comment by rsignell-usgs** [comment]
@ayan-usgs, your impression is correct.   There are many datasets with more than one standard_time variable:  whenever the data variables have different numbers of time steps, you will get different time coordinate variables, all with `standard_name='time'`. 

Check out `time` and `time1` in this dataset:
http://thredds.ucar.edu/thredds/dodsC/grib/NCEP/NAM/CONUS_12km/Best.html

**Comment by kwilcox** [comment]
@rsignell-usgs thanks I needed a test link

**Comment by ayan-usgs** [comment]
It doesn't look like http://thredds.ucar.edu/thredds/dodsC/grib/NCEP/NAM/CONUS_12km/Best.html is an SGRID compliant file.

**Comment by rsignell-usgs** [comment]
@ayan-usgs, nothing will be sgrid-compliant at this point besides stuff we create.  The rest of the world does not even know about SGRID!

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

That's true. I just brought it up because I wasn't sure if @kwilcox was looking for an SGRID compliant file with multiple variables with `standard_name = time` for testing purposes.

**Pull request merged**
