### PR TITLE
continue #129

### PR DESCRIPTION
**Pull request by ocefpaf**
@kwilcox this is what I had in line after #129 

It does not get a passing status yet but it creates a working env with minimum dependency updates so we can assess the issues better, before unpinning them all.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
Do we need to support python2?   
I notice a lot of `'str' object has no attribute 'decode'` errors like:
https://travis-ci.org/sci-wms/sci-wms/jobs/361212018#L1215-L1220

**Comment by ocefpaf** [comment]
> Do we need to support python2?

In my opinion it is not worth the effort.

**Comment by kwilcox** [comment]
@ocefpaf and I are nearly there with a clean build using modern external libs. The branch is going to remove support for anything less than 3.6. Upgrading piece by piece I only have matplotlib lib left...

**Comment by rsignell-usgs** [comment]
@kwilcox awesome!  This is exciting.   Looking forward, not backward!  😸

**Comment by ocefpaf** [comment]
Closing in favor of #131

Thanks for releasing most of the pins @kwilcox! That is a dream for packagers :smile:

**Pull request closed without merging**
