### PR TITLE
implemented some pyugrid components

### PR DESCRIPTION
**Pull request by ayan-usgs**
Non-UGRID compliant datasets are unsupported. Per disussions on Issue #6 that is considered okay.

### CODE REVIEW

**Comment by kwilcox** [comment]
@ayan-usgs Did you test this with non-UGRID datasets (for example, the CGRID dataset that is shipped with sci-wms)?  From what I can tell you have decided to normalize the topology cache as a UGRID dataset?  Not a bad idea, just wondering if its fully working before I test it.

**Comment by ayan-usgs** [comment]
@kwilcox,

The CGRID dataset is currently inoperable. It will raise an exception saying it is no standard-conforming meshes". I have yet to start work on SGRID/CGRID compatibility.

**Comment by kwilcox** [comment]
@ayan-usgs Before we merge this we need to establish a tagging/branch/release system.  I'm not comfortable merging everything into master and assuming someone coming in blind can figure out which commit is stable enough to run on their own. I'm swamped today but later this week I'll take a stab at it unless you want to in the meantime.

**Comment by ayan-usgs** [comment]
@kwilcox,

I created a tag https://github.com/sci-wms/sci-wms/tree/0.1 for the previous stable version last week so new comers have something operable that they can run. In general, as we continue development, I am thinking we can tag stable versions. I am on the fence about using branches... while I see them useful for developing new features and reducing "pollution" on master, I also feel that branching sometimes lends itself to unruly merges which itself introduces some risk.

But anyway, there is currently a tag for the last stable version.

**Comment by ayan-usgs** [comment]
Branched to 'pyugrid'.

**Pull request closed without merging**
