### PR TITLE
fixed incorrect slicing in sgrid variables with 3 dims

### PR DESCRIPTION
**Pull request by ayan-usgs**
bug fix for issue #74

### CODE REVIEW

**Comment by ayan-usgs** [comment]
Turns on the wrong index was being used.... :flushed:

**Comment by ayan-usgs** [comment]
@kwilcox,

Not too much changed here. Please have a look.

**Comment by kwilcox** [comment]
@ayan-usgs While reviewing this, I noticed that you are extracting the entire offset grid every request from the raw dataset.  We should be subsetting on data access (indexing) to lighten the load over the wire if the dataset is coming over DAP, and to speedup the viz process (matplotlib is doing the subsetting now).

Example that subsets before data access:

https://github.com/ayan-usgs/sci-wms/blob/eb01185ff9f0d56ac1a35b43670ef3bf948250aa/wms/models/datasets/sgrid.py#L154-L175

**Comment by ayan-usgs** [comment]
@kwilcox,

Thanks for the suggestion. I'll create an issue for this -- should be able to work on it in the next week or so.

**Pull request merged**
