### PR TITLE
Reduce the number of times app has to go out to threads for a remote sgrid dataset. Handling of datasets with more than one standard_name = time variable.

### PR DESCRIPTION
**Pull request by ayan-usgs**
Studying the performance through django-silk, it seems this saves between 10 - 25 seconds per tile on the leaflet client when on the DOI network. There's no significant change when requesting a WMS layer directly.

### CODE REVIEW

**Comment by ayan-usgs** [comment]
@kwilcox,

When you have a moment, can you take a look a this pull request? Any suggestions or thoughts you have regarding it would be greatly appreciated. I'm not sure if the changes I made were the best way to go about slow performance with remote datasets.

Thanks!

**Comment by ayan-usgs** [comment]
Amended to include code pertinent to #45.

**Comment by kwilcox** [comment]
@ayan-usgs, just a few comments:
- There are many commits in this PR that are already merged into rel-2.0, can you remove them? They were caused by this unneeded merge commit in your fork: https://github.com/ayan-usgs/sci-wms/commit/60a02ecfa53b200ba3e800603b0fc1aa30039ab7.
- You shouldn't need to check if a layer is a Layer or VirtualLayer, always use `layer.access_name` (VirtualLayers won't always use the `,` separator). https://github.com/ayan-usgs/sci-wms/commit/5e42951ea4e607aa3ed0241a40dfbec575ffd579#diff-285cca955f77d80ef937adfbf8a235baR176
- You should override the destructor method `__del__` here: https://github.com/ayan-usgs/sci-wms/commit/a36276a27581232c49179761f0ebe38ae4b577e2 and close the `canon_dataset` object.
- These commits could be rebased into 2 or 3 targeted commits

**Comment by ayan-usgs** [comment]
Closing for now.

**Pull request closed without merging**
