### PR TITLE
require Z suffix, remove tzinfo before passing to netCDF4.date2num

### PR DESCRIPTION
**Pull request by ayan-usgs**
fix for issue #76

### CODE REVIEW

**Comment by ayan-usgs** [comment]
@kwilcox,

Can you take a look at this when you have a moment? Comments or suggestions are appreciated as always.

Thanks!

**Comment by kwilcox** [comment]
Please remove the code that requires Z in the time parameter. It will break many clients. We should also convert to UTC before removing the timezone info so we always know we have a UTC naive datetime in UTC.

**Comment by ayan-usgs** [comment]
@kwilcox,

That code can be removed. 

Regarding the conversion of to UTC, how would you envision users specifying time in their zone of preference with a UTC offset, time zone abbreviation (e.g. EST, CST, etc), or military time zone codes (e.g. X, Y, Z, etc.)? Converting to UTC from another timezone would require sci-wms to be able deal with the myriad ways timezone can be represent. I prefer the offset option.

**Comment by kwilcox** [comment]
The "parse" function already parses just about every possible
representation, and I've got code that adds more functionality if we really
need it.

**Comment by ayan-usgs** [comment]
@kwilcox 

Thanks for the information. I still have my concerns about user specified timezones. Specifically, I'm not sure that datetutils `parse` handles timezone abbreviations without defining them _a priori_.

```
>>> from dateutil.parser import parse
>>> a = '2012-08-15T16:00:00-05:00'
>>> dt1 = parse(a)
>>> print(dt1)
2012-08-15 16:00:00-05:00
>>> print(dt1.tzinfo)
tzoffset(None, -18000)
>>> b = '2012-08-15T16:00:00CDT'
>>> dt2 = parse(b)
>>> print(dt2)
>>> 2012-08-15 16:00:00
>>> print(dt2.tzinfo)
>>> None
from dateutil.tz import gettz
>>> tz_dict = {'CDT': gettz('America/Chicago')}
>>> dt3 = parse(b, tzinfos=tz_dict)
>>> print(dt3)
2012-08-15 16:00:00-05:00
>>> print(dt3.tzinfo)
tzfile('US/Central')
```

We can define them, but there are many ways to abbreviate timezones.

**Pull request merged**
