### PR TITLE
Timeperiods in GetCaps. Fixes #65.

### LINKED ISSUE #65: Expressing time values in getCapabilities
For our COAWST forecast model, the NcWMS getCaps 
http://geoport.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?service=WMS&version=1.3.0&request=GetCapabilities
show times like this:

```
<Dimension name="time" units="ISO8601" multipleValues="true" current="true" default="2015-07-30T14:00:00.000Z">
2012-06-25T01:00:00.000Z/2012-06-26T00:00:00.000Z/PT1H,2012-06-27T01:00:00.000Z/2012-06-30T00:00:00.000Z/PT1H,2012-07-02T01:00:00.000Z/2012-07-03T00:00:00.000Z/PT1H,2012-07-05T01:00:00.000Z/2012-07-09T00:00:00.000Z/PT1H,2012-07-10T01:00:00.000Z/2012-07-14T00:00:00.000Z/PT1H,2012-07-17T01:00:00.000Z/2012-07-18T00:00:00.000Z/PT1H,2012-07-19T01:00:00.000Z/2012-08-14T00:00:00.000Z/PT1H,
...
</Dimension>
```

while the sci-wms getCaps:
http://sci-wms.whoi.edu/wms/datasets/coawst?REQUEST=GetCapabilities
doesn't seem to show any intervals, and shows only an extent:

```
<Dimension name="time" units="ISO8601" />
<Extent name="time">2012-06-25T01:00:00Z/2015-07-31T00:00:00Z</Extent>
```

Should we be including the intervals, just as ncWMS is doing?

```


```

### PR DESCRIPTION
**Pull request by kwilcox**

### CODE REVIEW

**Comment by kwilcox** [comment]
I forgot the `isodate` dependency (which isn't in conda :sob:). Should pass now.

**Comment by ocefpaf** [comment]
> I forgot the isodate dependency (which isn't in conda :sob:). Should pass now.

It is in there:

``` bash
> conda search isodate
Fetching package metadata: ......
isodate                      0.4.9                    py27_0  ioos            
                             0.5.1                    py27_0  ioos            
                             0.5.1                    py27_1  ioos
```

As well as: `django-grappelli`, `django-typed-models`, `django-extensions`, `django-debug-toolbar`, and `django-autoslug`. (But no `pytest-django` yet.)

**Comment by kwilcox** [comment]
I must have been on a py3 venv when I tried!

**Comment by ocefpaf** [comment]
Touché.  I will added those to the py3 ToDo list.

**Comment by ocefpaf** [comment]
Python 2.7 and 3.4 versions of all the dependencies listed in

https://github.com/sci-wms/sci-wms/blob/master/.travis.yml#L33-L34

are now available in the IOOS channel.  Let me know how it goes if you try them out.

**Comment by kwilcox** [comment]
@ocefpaf I cleaned what I could in the travis config, but I couldn't use conda to install `django-extensions` or `django-debug-toolbar` becasue they would replace the Django version with 1.8.x.  I looked at it for a few hours on a Friday and couldn't quickly fix it so reverted to `pip` for those.

**Comment by ocefpaf** [comment]
I guess we have to pin the `Django` version down in the `django-extensions` and `django-debug-toolbar` recipes (`django >=1.7,<1.8`, right?).  I will do that and get back to you.

**Pull request merged**
