### PR TITLE
Functional improvements to act more like ncWMS

### PR DESCRIPTION
**Pull request by kwilcox**

### CODE REVIEW

**Comment by kwilcox** [comment]
@ayan-usgs please review

**Comment by ayan-usgs** [comment]
@kwilcox,

Looks good to go.

**Comment by rsignell-usgs** [comment]
@ayan-usgs, does this mean you tested it?

On Mon, Apr 13, 2015 at 11:41 AM, ayan-usgs notifications@github.com
wrote:

> @kwilcox https://github.com/kwilcox,
> 
> Looks good to go.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sci-wms/sci-wms/pull/30#issuecomment-92406557.

## 

Dr. Richard P. Signell   (508) 457-2229
USGS, 384 Woods Hole Rd.
Woods Hole, MA 02543-1598

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

It means I reviewed the source code for things like obvious logic errors, tests for new code components, readability, and conformity to PEP8. I did not run the code myself.

**Pull request merged**
