### PR TITLE
Integration of COMT, pyugrid, and stable branches

### PR DESCRIPTION
**Pull request by kwilcox**
This represents the next community release of sci-wms (rel-2.0).

I've pulled in the`GetMap` portions of the `comt` branch (removed `basemap`, etc.).  I still need to get `GetLegendGraphic` and `GetFeatureInfo` working.

sci-wms only supports a limited number of styles now (`filledcontours` and `vectors`).  We really need a `facets` or `pcolor` in here but I'm not the guy to do it.  @rsignell-usgs?  @acrosby?

sci-wms only supports `UGRID` datasets now. @ayan-usgs is working on the `sgrid` library that will provide more support in the future.  If someone wanted to write in `rgrid` support I would give them some hugs.

This is a major overhaul but will provide us with a nice starting point for future development..  I'll go over the changes on the call tomorrow (Thursday, May 7th).

Comments appreciated!

### CODE REVIEW

**Comment by acrosby** [comment]
if it is obvious how to add styles to the new codebase, i can get a pcolor for ugrid going

**Comment by rsignell-usgs** [comment]
@acrosby , perhaps @kwilcox can address this in the 3pm telecon.   I hope you can join us.

**Comment by kwilcox** [comment]
The `pcolor_[colormap]` styles are already available in the codebase, you would just need to check for `image_type == 'pcolor'` around here: https://github.com/axiom-data-science/sci-wms/blob/demo/wms/models/datasets/ugrid.py#L134 and create a function in mpl_handler.py that does the drawing.

**Comment by acrosby** [comment]
alright, ill take a look once this is merged. there have been some changes (in our favor) to the mpl functions that i'm not sure had yet been included in sci-wms.

**Comment by acrosby** [comment]
@kwilcox what's the timeline for getting this merged in or is it still a WIP?

**Comment by rsignell-usgs** [comment]
This build is erroring because of an HDF5 install error.    Let's use the binstar ioos channel at binstar.org/ioos to install the dependencies via conda!    

@kwilcox, this list isn't correct anymore, right?:
https://github.com/ioos/conda-recipes/blob/master/sci-wms-deps/meta.yaml#L19-L39

**Comment by ayan-usgs** [comment]
I think the command: `pip install git+https://github.com/axiom-data-science/pyaxiom.git` in `.travis.yml` should actually be `pip install -e git+https://github.com/axiom-data-science/pyaxiom.git@master#egg=pyaxiom`. It doesn't have to be the master branch, but I think pip expected a command of this format.

**Comment by ayan-usgs** [comment]
@kwilcox,

The removal of wms_request.py may cause some heartburn when views.py line 56 tries:

```
import wms.wms_requests as wms_reqs
```

**Comment by ayan-usgs** [comment]
@kwilcox,

Okay, that makes sense.

Regarding the `import wms.wms_requests as wms_req` -- the group view still uses it, despite the removal of the module. While I've not had a need to use that particular view, I'm not totally comfortable having a view that relies on a import that would cause fail. What are your thoughts?

**Comment by rsignell-usgs** [comment]
@ayan-usgs, have you been able to successfully install and test this PR? 
Please document any issues you had (or better yet, just fix the documentation!)

**Comment by ayan-usgs** [comment]
@rsignell-usgs  and @kwilcox,

I did get this pull request to run locally using the Django dev server. I needed to make the following changes before it worked:
- comment out the `ugrid` import from `cgrid.py` -- it actually will error if you leave it
- comment out the `wms.wms_request` import from `views.py` -- again it will error if left in place

**Comment by kwilcox** [comment]
Please submit changes to the `rel-2.0` branch.  Yes, it is still `rel-2.0`, but don't worry about the name.

**Pull request merged**
