### PR TITLE
Update external libraries and python to 3.6

### PR DESCRIPTION
**Pull request by kwilcox**

### CODE REVIEW

**Comment by kwilcox** [comment]
@ocefpaf This is ready for merge if you :+1:

**Comment by ocefpaf** [comment]
I don't have commit rights here, sorry @kwilcox.

**Comment by rsignell-usgs** [comment]
I don't see anything wrong here.  😸

**Comment by rsignell-usgs** [comment]
So there is still a dependence on axiom channel?
https://github.com/sci-wms/sci-wms/blob/master/Dockerfile#L42

**Comment by kwilcox** [comment]
No, it builds without it. Didn't catch that. Will remove in future pr

**Comment by rsignell-usgs** [comment]
I've updated https://gamone.whoi.edu/wms with the [latest Docker container](https://hub.docker.com/r/axiom/sci-wms/tags/) and it's working great.  No problem with zeros on color limits:

**Pull request merged**
